export const LOGIN_PROCESS = 'LOGIN_PROCESS'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT_PROCESS = 'LOGOUT_PROCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const CHANGE_PROFILE_PROCESS = 'CHANGE_PROFILE_PROCESS'
export const CHANGE_PROFILE_SUCCESS = 'CHANGE_PROFILE_SUCCESS'
export const CHANGE_PROFILE_FAIL = 'CHANGE_PROFILE_FAIL'
