export const GET_CATEGORY_NEWS_PROCESS = 'GET_CATEGORY_NEWS_PROCESS'
export const GET_CATEGORY_NEWS_SUCCESS = 'GET_CATEGORY_NEWS_SUCCESS'
export const GET_CATEGORY_NEWS_FAIL = 'GET_CATEGORY_NEWS_FAIL'

export const GET_CATEGORY_UMKM_PROCESS = 'GET_CATEGORY_UMKM_PROCESS'
export const GET_CATEGORY_UMKM_SUCCESS = 'GET_CATEGORY_UMKM_SUCCESS'
export const GET_CATEGORY_UMKM_FAIL = 'GET_CATEGORY_UMKM_FAIL'

export const GET_CATEGORY_BUYER_PROCESS = 'GET_CATEGORY_BUYER_PROCESS'
export const GET_CATEGORY_BUYER_SUCCESS = 'GET_CATEGORY_BUYER_SUCCESS'
export const GET_CATEGORY_BUYER_FAIL = 'GET_CATEGORY_BUYER_FAIL'

export const GET_CATEGORY_STAKEHOLDER_PROCESS =
  'GET_CATEGORY_STAKEHOLDER_PROCESS'
export const GET_CATEGORY_STAKEHOLDER_SUCCESS =
  'GET_CATEGORY_STAKEHOLDER_SUCCESS'
export const GET_CATEGORY_STAKEHOLDER_FAIL = 'GET_CATEGORY_STAKEHOLDER_FAIL'

export const GET_CATEGORY_COURSES_PROCESS = 'GET_CATEGORY_COURSES_PROCESS'
export const GET_CATEGORY_COURSES_SUCCESS = 'GET_CATEGORY_COURSES_SUCCESS'
export const GET_CATEGORY_COURSES_FAIL = 'GET_CATEGORY_COURSES_FAIL'
