export const GET_SLUG_NEWS_PROCESS = 'GET_SLUG_NEWS_PROCESS'
export const GET_SLUG_NEWS_SUCCESS = 'GET_SLUG_NEWS_SUCCESS'
export const GET_SLUG_NEWS_FAIL = 'GET_SLUG_NEWS_FAIL'

export const GET_SLUG_COURSE_PROCESS = 'GET_SLUG_COURSE_PROCESS'
export const GET_SLUG_COURSE_SUCCESS = 'GET_SLUG_COURSE_SUCCESS'
export const GET_SLUG_COURSE_FAIL = 'GET_SLUG_COURSE_FAIL'

export const GET_SLUG_STAKEHOLDER_PROCESS = 'GET_SLUG_STAKEHOLDER_PROCESS'
export const GET_SLUG_STAKEHOLDER_SUCCESS = 'GET_SLUG_STAKEHOLDER_SUCCESS'
export const GET_SLUG_STAKEHOLDER_FAIL = 'GET_SLUG_STAKEHOLDER_FAIL'

export const GET_SLUG_BUYER_PROCESS = 'GET_SLUG_BUYER_PROCESS'
export const GET_SLUG_BUYER_SUCCESS = 'GET_SLUG_BUYER_SUCCESS'
export const GET_SLUG_BUYER_FAIL = 'GET_SLUG_BUYER_FAIL'

export const GET_SLUG_UMKM_PROCESS = 'GET_SLUG_UMKM_PROCESS'
export const GET_SLUG_UMKM_SUCCESS = 'GET_SLUG_UMKM_SUCCESS'
export const GET_SLUG_UMKM_FAIL = 'GET_SLUG_UMKM_FAIL'
