export const GET_DETAIL_NEWS_PROCESS = 'GET_DETAIL_NEWS_PROCESS'
export const GET_DETAIL_NEWS_SUCCESS = 'GET_DETAIL_NEWS_SUCCESS'
export const GET_DETAIL_NEWS_FAIL = 'GET_DETAIL_NEWS_FAIL'

export const GET_DETAIL_COURSE_PROCESS = 'GET_DETAIL_COURSE_PROCESS'
export const GET_DETAIL_COURSE_SUCCESS = 'GET_DETAIL_COURSE_SUCCESS'
export const GET_DETAIL_COURSE_FAIL = 'GET_DETAIL_COURSE_FAIL'

export const GET_DETAIL_STAKEHOLDER_PROCESS = 'GET_DETAIL_STAKEHOLDER_PROCESS'
export const GET_DETAIL_STAKEHOLDER_SUCCESS = 'GET_DETAIL_STAKEHOLDER_SUCCESS'
export const GET_DETAIL_STAKEHOLDER_FAIL = 'GET_DETAIL_STAKEHOLDER_FAIL'

export const GET_DETAIL_BUYER_PROCESS = 'GET_DETAIL_BUYER_PROCESS'
export const GET_DETAIL_BUYER_SUCCESS = 'GET_DETAIL_BUYER_SUCCESS'
export const GET_DETAIL_BUYER_FAIL = 'GET_DETAIL_BUYER_FAIL'

export const GET_DETAIL_UMKM_PROCESS = 'GET_DETAIL_UMKM_PROCESS'
export const GET_DETAIL_UMKM_SUCCESS = 'GET_DETAIL_UMKM_SUCCESS'
export const GET_DETAIL_UMKM_FAIL = 'GET_DETAIL_UMKM_FAIL'
